sudo: true
os: linux
language: cpp
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgtest-dev
script:
 - make test

after_success:
  - echo "success"
after_failure:
  - echo "failure"

