sudo: true
os: linux
language: cpp
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y libgtest-dev
  - sudo apt-get install -y g++-6
script:
 - make test

after_success:
  - echo "success"
after_failure:
  - echo "failure"
