sudo: true
os: linux
language: cpp
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y libgtest-dev
  - sudo apt-get install -y g++-7
  - sudo apt-get install -y cmake
  - sudo apt-get install -y lcov
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make -j 16
  - sudo cp *.a /usr/lib
  - sudo mkdir /usr/local/lib/gtest
  - sudo ln -s /usr/lib/libgtest.a /usr/local/lib/gtest/libgtest.a
  - sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/gtest/libgtest_main.a
  - cd -
script:
 - make run_test
 - make clean
 - make config=debug coverage
 - make clean
 - make perf
 - ./main-perf

after_success:
  - echo "success"
after_failure:
  - echo "failure"
